# docker build . -t sei-protocol/sei:latest
# docker run --rm -it sei-protocol/sei:latest /bin/sh
FROM golang:1.24.5-alpine AS go-builder

# this comes from standard alpine nightly file
#  https://github.com/rust-lang/docker-rust-nightly/blob/master/alpine3.12/Dockerfile
# with some changes to support our toolchain, etc
SHELL ["/bin/sh", "-ecuxo", "pipefail"]
# we probably want to default to latest and error
# since this is predominantly for dev use
# hadolint ignore=DL3018
RUN apk add --no-cache ca-certificates build-base git
# NOTE: add these to run with LEDGER_ENABLED=true
# RUN apk add libusb-dev linux-headers

WORKDIR /code

# Download dependencies and CosmWasm libwasmvm if found.
ADD go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    set -eux; \
    export ARCH=$(uname -m); \
    # Currently github.com/CosmWasm/wasmvm is being overriden by github.com/sei-protocol/sei-wasmvm
    # (see go.mod). However the rust precompiles are still fetched from the upstream repository.
    # Here we assume that the sei-wasm release version is prefixed with the wasmvm release version
    # with the matching precompiles. Therefore, to compute the download url, we just strip the suffix
    # of the sei-wasm release version.
    WASM_VERSION=$(go list -f {{.Replace.Version}} -m github.com/CosmWasm/wasmvm | sed s/-.*//); \
    if [ ! -z "${WASM_VERSION}" ]; then \
    wget -O /lib/libwasmvm_muslc.a https://github.com/CosmWasm/wasmvm/releases/download/${WASM_VERSION}/libwasmvm_muslc.${ARCH}.a; \
    fi; \
    wget -O /lib/libwasmvm152_muslc.a https://github.com/sei-protocol/sei-wasmd/releases/download/v0.3.6/libwasmvm152_muslc.${ARCH}.a; \
    wget -O /lib/libwasmvm155_muslc.a https://github.com/sei-protocol/sei-wasmd/releases/download/v0.3.6/libwasmvm155_muslc.${ARCH}.a; \
    go mod download;

# Copy over code
COPY . /code/

# force it to use static lib (from above) not standard libgo_cosmwasm.so file
# then log output of file /code/build/seid
# then ensure static linking
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    LEDGER_ENABLED=false BUILD_TAGS=muslc LINK_STATICALLY=true make build-verbose -B \
    && file /code/build/seid \
    && echo "Ensuring binary is statically linked ..." \
    && (file /code/build/seid | grep "statically linked")

# --------------------------------------------------------
# Firehose Additions
#
# Everything above this can be copied mostly straight from ./Dockerfile
# (expect the final FROM alpine:3.18 image that is removed and replaced by
# our own stuff below).
# --------------------------------------------------------

FROM ubuntu:24.04 AS base

WORKDIR /app

RUN apt-get update && apt-get install -y apt-transport-https ca-certificates curl gnupg tar jq vim wget

RUN curl -LO https://github.com/chmln/sd/releases/download/v1.0.0/sd-v1.0.0-x86_64-unknown-linux-gnu.tar.gz \
    && tar -xzf sd-v1.0.0-x86_64-unknown-linux-gnu.tar.gz \
    && cp sd-v1.0.0-x86_64-unknown-linux-gnu/sd /usr/local/bin/sd \
    && rm -rf sd-v1.0.0-x86_64-unknown-linux-gnu sd-v1.0.0-x86_64-unknown-linux-gnu.tar.gz

ENV PATH="/app:${PATH}"

FROM ghcr.io/streamingfast/firehose-ethereum:latest

COPY --from=go-builder /code/build/seid /app/seid

RUN chmod +x /app/seid
